### ISSUE TITLE
Code cleaning

### ISSUE THREAD

**Issue by Ishaan28malik** [Ishaan28malik/react-conference-web-app#7]
### Clean the code by removing the unused variables or files or comments.
* but make sure not to remove all unused files because there are a few that are still getting updated.

**Comment by PseudoNerd** [comment]
Can I take this up ?

**Comment by Ishaan28malik** [comment]
@PseudoNerd sure go ahead.

**Comment by ishaanLuke24** [comment]
@Ishaan28malik I want to work on this.

**Comment by Ishaan28malik** [comment]
> @Ishaan28malik I want to work on this.

sure.

**Comment by ishaanLuke24** [comment]
@Ishaan28malik please check #9
